### ISSUE TITLE
Crouch image not working

### ISSUE THREAD

**Issue by Akhilknowsdawae** [imd1005-web-development-winter-2023/group-project-dobytes#10]
## Description

Hello @neilmispelaar, I'm back into more javascript problems 😭!
The crouch image isn't working. It shows up as a file image-looking thing instead. I tried increasing/decreasing the image height/width.

## Screenshot
![image](https://user-images.githubusercontent.com/22270009/230809249-4a0ea33c-ed2b-43ae-abec-d7964af7507b.png)

https://user-images.githubusercontent.com/22270009/230809258-2d378ad2-151b-48d0-aad9-a95ed9a3ece7.mp4

**Comment by neilmispelaar** [comment]
Hey @Akhilknowsdawae - I’ll have to pick this up first thing in the morning. 

Also, just so you are aware “vh” (vertical height) is based on the browser height, so if someone makes their browser taller or shorter it will change the size of your element.

**Comment by neilmispelaar** [comment]
Hi @Akhilknowsdawae 

I think this is the same issue as I mentioned in my other comment. 

Try adding a `.` (dot) before the path to the image. 


```js
playerImage.src="./sprites/Brown/AmongUsCrouch2.png"; // Note that it now starts with a dot .
```

**Comment by neilmispelaar** [comment]
Let me know if that fixes things
