### ISSUE TITLE
Sprite colors after color select not appearing

### ISSUE THREAD

**Issue by Akhilknowsdawae** [imd1005-web-development-winter-2023/group-project-dobytes#11]
# Issue

## Description
We're trying to change the gif used in the game based on the color choice of the player, but for some reason, it only works when the brown color is selected. Other color sprites don't appear at all. 

## Screenshot
query selector of 'playerimage' 
![image](https://user-images.githubusercontent.com/22270009/230813320-e779e10e-de7b-456f-89c0-f575efd32d58.png)

The array of walking sprites
![image](https://user-images.githubusercontent.com/22270009/230813337-3499c8af-247d-4d27-a413-a6f22f3c5228.png)

colorIndex constant (it works)
![image](https://user-images.githubusercontent.com/22270009/230813809-09fdbf6d-1b9e-4081-99fa-cdc7e96ce049.png)

changing the img source based off the local storage index
![image](https://user-images.githubusercontent.com/22270009/230813883-c2d9acf7-3ea7-4933-b7bd-f0a6fb507404.png)

initializing

**Comment by neilmispelaar** [comment]
Hey @Akhilknowsdawae 

Remember paths in GitHub pages should start with `./` or just not include a forward slash `/`

Your array: 

```js
let colourWalkSprites = [
"/sprites/Brown/brownrun.gif",
"/sprites/LightBlue/bluerun.gif",
"/sprites/Pink/pinkrun.gif".
"/sprites/green/greenrun.gif"]
```

I'm wondering if the paths should be **(Note: I added a dot (.) before the slash)**: 

```js
let colourWalkSprites = [
"./sprites/Brown/brownrun.gif",
"./sprites/LightBlue/bluerun.gif",
"./sprites/Pink/pinkrun.gif".
"./sprites/green/greenrun.gif"]
```

**Comment by neilmispelaar** [comment]
Also @Akhilknowsdawae strongly recommend all of your files and paths are lowercase. (This is only a recommendation)

**Comment by Akhilknowsdawae** [comment]
Hello again @neilmispelaar ! I've edited the code to how you suggested but it didn't fix the problem. But the dead sprites are appearing in the correct color which is progress. This there any sort of precautions that should be taken when working with gifs? 

![image](https://user-images.githubusercontent.com/22270009/231017109-460a9f8f-3905-494a-bcba-024a2887452e.png)
![image](https://user-images.githubusercontent.com/22270009/231017124-5dfc1e26-a40c-4226-91bf-931b6e4c145e.png)

**Comment by neilmispelaar** [comment]
@Akhilknowsdawae 

Hmmmmm. 

Okay I’ll open up your code. 

In the interim, can you console log how you are calculating the Index for the walking sprites and drop a screenshot of the browser consol log output. 

Wherever your setting the image SRC just console log ( image SRC, and the Index value)

**Comment by Akhilknowsdawae** [comment]
@neilmispelaar 

I put in a console log
![image](https://user-images.githubusercontent.com/22270009/231020281-13205b21-b457-4491-a066-dec08581458d.png)

Weird thing, it only works for the brown color (index 0)
![image](https://user-images.githubusercontent.com/22270009/231020165-f7913166-695e-4eb6-9dd1-4d1d618009b9.png)
![image](https://user-images.githubusercontent.com/22270009/231020231-35388d1c-1077-40b5-983a-2a6e0a36fa01.png)

But not for the other colors (Index 1)
![image](https://user-images.githubusercontent.com/22270009/231020518-91b9bff8-756c-406a-9be0-d643eba66a5c.png)
![image](https://user-images.githubusercontent.com/22270009/231020555-58cbdb8c-c101-4623-a155-2bae4a96f716.png)
![image](https://user-images.githubusercontent.com/22270009/231020729-2ddcfddd-484d-44cf-9ab0-b1522917d787.png)

**Comment by neilmispelaar** [comment]
Okay, something is causing this...

<img width="506" alt="Screenshot 2023-04-10 at 7 58 48 PM" src="https://user-images.githubusercontent.com/9325038/231021590-2281167a-d775-40d4-a53b-313cd6030b87.png">

**Comment by neilmispelaar** [comment]
Hey @Akhilknowsdawae 

What do you notice :-) 

<img width="372" alt="Screenshot 2023-04-10 at 8 00 13 PM" src="https://user-images.githubusercontent.com/9325038/231021724-216b3c51-6675-422f-935e-7a22378b40e1.png">

**Comment by neilmispelaar** [comment]
<img width="927" alt="Screenshot 2023-04-10 at 8 02 26 PM" src="https://user-images.githubusercontent.com/9325038/231021947-1f2c166a-3878-4a78-b65d-3081013d6a71.png">

**Comment by neilmispelaar** [comment]
Let me know if that solves the issue. 

Do the other sprites work? (Apart from Blue / LightBlue)

**Comment by Akhilknowsdawae** [comment]
Oh haha, we noticed that yesterday and fixed it. We didn't sync the changes though. But it still doesn't work ._ .

We're kind of lost right now cause the only things left we need to do is some CSS and adding images which isn't working D:

**Comment by neilmispelaar** [comment]
Could it be how the gifs were generated? 

Can you test with other known good gifs?

Notice how in GitHub one gif is displayed and one gif shows a bunch of text. 

<img width="1291" alt="Screenshot 2023-04-10 at 8 38 51 PM" src="https://user-images.githubusercontent.com/9325038/231025850-5576c31d-e4be-4317-aa24-e32b32fe2f8d.png">


<img width="1291" alt="Screenshot 2023-04-10 at 8 39 02 PM" src="https://user-images.githubusercontent.com/9325038/231025957-df603418-66be-4af8-acf4-4387958aff1e.png">

**Comment by neilmispelaar** [comment]
<img width="1617" alt="Screenshot 2023-04-10 at 8 41 02 PM" src="https://user-images.githubusercontent.com/9325038/231026113-47bf9705-0cdf-4e16-9937-356727c8edb7.png">

**Comment by Akhilknowsdawae** [comment]
It finally works! Apparently uploading files through a liveshare workspace screw up the images/gifs. I got it to work! I'll be leaving this issue open just in case we run into more problems. Thank you so much! 

I also have another question regarding responsiveness. 

We have a video background but whenever we reduce the screen size, it has a fixed resolution. Is there a way for it to change the resolution of the video background?

**Comment by neilmispelaar** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit

Try the `object-fit: cover` CSS property 

I’m not 100% it will work but that’s likely your best bet.
