### ISSUE TITLE
page music

### ISSUE THREAD

**Issue by fay-bug** [imd1005-web-development-winter-2023/group-project-dobytes#12]
# Issue

## Description

I am trying to add music in the page, but it doesn't work when you first load up the page, I have to click play button then back button then the music plays, but I'm trying to make it play on page load automatically.
In index.html I tried these but they both have the same problem.

## Screenshot
![image](https://user-images.githubusercontent.com/122563391/230827885-04a477ff-bfc8-4466-bfee-f16f80795862.png)
![image](https://user-images.githubusercontent.com/122563391/230828123-1635a49b-ab6a-4b07-b9d4-9409da164156.png)

**Comment by neilmispelaar** [comment]
Hey @aura-git 

Can you please kindly do a `console.log(audio)` on the line after `const audio = document.querySelector "audio");`

I have a feeling your `audio` variable is `null` because the `document.querySelector("audio");` can't find an element called "audio".

**Comment by fay-bug** [comment]
hi @neilmispelaar 
I just tried doing that but there is still the same problem 
![image](https://user-images.githubusercontent.com/122563391/231016549-89ad77ed-2fc2-4273-bf04-d6af912f60a2.png)

**Comment by neilmispelaar** [comment]
Hi @aura-git 

Sorry, can you share a screenshot of the Browser console log. 

I’d like to see if it throws an error (and what the error says)

**Comment by fay-bug** [comment]
![image](https://user-images.githubusercontent.com/122563391/231016901-a5e6135b-bd76-45cf-9b1d-02c040f58c7b.png)

**Comment by fay-bug** [comment]
Does that mean I have to add a play music button?

**Comment by neilmispelaar** [comment]
@aura-git 

Oh snap, can we not auto play an audio file? 

This might need some googling on my part

**Comment by neilmispelaar** [comment]
@aura-git 

Yes. 

We might need a button to start the audio as opposed to automatically playing the audio file.

**Comment by fay-bug** [comment]
I see, thanks!

**Comment by neilmispelaar** [comment]
Here are the docs on Auto play if this ever comes up for you in the future: 

https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide

Basically, until a user interacts with the page (for example clicks anything on the page) , any auto play (video or audio) will be blocked.

So yeah, sadly the you might need a button to let the user start playing music.
