### ISSUE TITLE
Commit Failed

### ISSUE THREAD

**Issue by Akhilknowsdawae** [imd1005-web-development-winter-2023/group-project-dobytes#13]
# Issue

## Description
@neilmispelaar 
We're trying to upload/update sprites but whenever we try to commit, it takes a long time to process the file and fails.

## Screenshot

![image](https://user-images.githubusercontent.com/22270009/231067160-56891cfc-46cc-45ca-a7e9-13a01d374f9c.png)

**Comment by neilmispelaar** [comment]
Hey @Akhilknowsdawae 

Is this still an issue? It's possible GitHub was doing some maintenance during the middle of the night that you hit. 

I can give you a bit more time to get things submitted but your demo will have to go as is.

**Comment by Akhilknowsdawae** [comment]
Hello @neilmispelaar , we fixed the commit issue but we are running into a few problems regarding the images again. It works completely fine in our live server share but when we sync the changes and open the Github page, a few images doesn't seem to appear.
