### ISSUE TITLE
Local Storage

### ISSUE THREAD

**Issue by Lenibi** [imd1005-web-development-winter-2023/group-project-dobytes#7]
Hi @neilmispelaar,

How does local storage work?
I am trying to keep some variables in local storage.

I know about localStorage.setItem(key, value); and localStorage.getItem(key);
But how do I make the variable in the first place?

**Comment by neilmispelaar** [comment]
Hi @Lenibi 

Here is a small demo (link below) 

You don't actually "create" a variable. You just use the `localStorage` object in your code to get and set values. When you use `localStorage.getItem(...)` you save the incoming value to a local variable.  

You can also access the values in the inspector which is super helpful: 

https://github.com/imd1005-web-development-winter-2023/class-code-examples/tree/main/class-25/local-storage-demo

<img width="1405" alt="Screenshot 2023-04-07 at 5 42 06 PM" src="https://user-images.githubusercontent.com/9325038/230682439-12b299ca-6b36-4222-9009-68a405105558.png">

**Comment by Lenibi** [comment]
Thank you! I know how to use local storage now
