### ISSUE TITLE
Accessing highest score from highScore array? in local storage

### ISSUE THREAD

**Issue by Lenibi** [imd1005-web-development-winter-2023/group-project-dobytes#9]
# Issue

Hi Neil, I want to set a text to the highest score in highScores from local storage.
I think it is an array of object literals.
How do I access the Score: value from the 0th term?
Also if highScores does not exist yet, I want the text to be 0

![image](https://user-images.githubusercontent.com/121530588/230802115-bb935e68-50d4-4639-bc6b-3af774282e50.png)

![image](https://user-images.githubusercontent.com/121530588/230802058-739c31f5-ab30-4fca-946c-3b4f31853989.png)

Code is in line 46 in main.js
The highScores is created in a function on line 638 in main.js

**Comment by neilmispelaar** [comment]
I’ll get you a more fulsome answer later tonight, but the long and short of it is this: 

```js

let names = [];
names[0] = prompt("New member name?");
localStorage.setItem("names", JSON.stringify(names));

//...
let storedNames = JSON.parse(localStorage.getItem("names"));

```

https://stackoverflow.com/questions/3357553/how-do-i-store-an-array-in-localstorage

**Comment by Lenibi** [comment]
The array is already made though i just dont know how to access the value

**Comment by Lenibi** [comment]
I fixed it
i was just missing json parse
